spring.application.name=rasxodbot
server.port=${PORT:8080}
spring.jpa.show-sql=true
spring.sql.init.mode=never
spring.datasource.password=SIVDsZEmLSbNtdaNGWRRUWXiOnTYVmqO
spring.datasource.username=railway
spring.datasource.url=jdbc:postgresql://turntable.proxy.rlwy.net:34574/railway
spring.jpa.hibernate.ddl-auto=create
spring.datasource.driver-class-name=org.postgresql.Driver
spring.data.rest.base-path=/v1/api
bot.name=oylikrasxodlar_bot
bot.token=8578108726:AAGnD-POhYSoowVDYeMQEa79acQWWZjOvdw
