spring.application.name=rasxodbot
server.port=80
spring.jpa.show-sql=true
spring.sql.init.mode=never
spring.datasource.password=root123
spring.datasource.username=postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/rasxod
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver
spring.data.rest.base-path=/v1/api
bot.name=oylikrasxodlar_bot
bot.token=8578108726:AAGnD-POhYSoowVDYeMQEa79acQWWZjOvdw
